### PR TITLE
Update libpq dependency

### PR DESCRIPTION
**Pull request by fhoehle**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by FelixHoehleQC** [comment]
@conda-forge/r-rpostgres please review and merge. Thanks!

**Comment by fhoehle** [comment]
@conda-forge/r-rpostgres please review and merge. Thanks.

**Comment by jdblischak** [comment]
@fhoehle Could you please provide some more context on what you are trying to accomplish with this PR? The [libpq recipe](https://github.com/conda-forge/libpq-feedstock/) hasn't been updated in 2 years, and [libpq is not included](https://github.com/conda-forge/libpq-feedstock/) in the conda-forge pinnings. Thus I wouldn't expect the libpq dependency to change.

**Comment by fhoehle** [comment]
> @fhoehle Could you please provide some more context on what you are trying to accomplish with this PR? The [libpq recipe](https://github.com/conda-forge/libpq-feedstock/) hasn't been updated in 2 years, and [libpq is not included](https://github.com/conda-forge/libpq-feedstock/) in the conda-forge pinnings. Thus I wouldn't expect the libpq dependency to change.

Hi @jdblischak the [libpq](https://github.com/conda-forge/libpq-feedstock/) was not updated since it is archived. The `r-rpostgres` recipe is depending on the [libpq generated by postgresql](https://github.com/conda-forge/postgresql-feedstock/blob/master/recipe/meta.yaml) via run export pinnings.
Also running running `conda search r-rpostgres --info` will print detailed dependency information including pinnings.
Cheers!

**Comment by jdblischak** [comment]
> The r-rpostgres recipe is depending on the libpq generated by postgresql via run export pinnings.
Also running running conda search r-rpostgres --info will print detailed dependency information including pinnings.

@fhoehle Thanks for the explanation!

I must admit I'm still confused. libpq is a runtime dependency of r-rpostgres, not a build dependency. Thus the latest version of libpq is installed when installing the current version of r-rpostgres. 

```
$ conda create --dry-run -n test-rpostgres r-rpostgres 2> /dev/null | grep libpq
    libpq-11.4                 |       hd9ab2ff_2         2.4 MB  conda-forge
  libpq              conda-forge/linux-64::libpq-11.4-hd9ab2ff_2
```

Is libpq also used during the compilation of r-rpostgres?

**Comment by fhoehle** [comment]
> @fhoehle Thanks for the explanation!
> 
> I must admit I'm still confused. libpq is a runtime dependency of r-rpostgres, not a build dependency. Thus the latest version of libpq is installed when installing the current version of r-rpostgres.
> 
> ```
> $ conda create --dry-run -n test-rpostgres r-rpostgres 2> /dev/null | grep libpq
>     libpq-11.4                 |       hd9ab2ff_2         2.4 MB  conda-forge
>   libpq              conda-forge/linux-64::libpq-11.4-hd9ab2ff_2
> ```
@jdblischak I think you have a local version of `r-rpostgres` which was compiled using `libpq-11.4`. 
Executing `conda search r-rpostgres --info -c conda-forge/linux-64` no recent `r-rpostgres` compatible with `libpq-11.4` is listed.
The explicit pinning `libpq` of `r-rpostgres` is also given in the `recipe/meta.yaml` of the latest [r-rpostgres package](https://anaconda.org/conda-forge/r-rpostgres/1.1.1/download/linux-64/r-rpostgres-1.1.1-r351h29659fb_1001.tar.bz2)
```
...
requirements:
...
    run:
        - libgcc-ng >=7.3.0
        - libpq >=10.5,<11.0a0
        - libstdcxx-ng >=7.3.0
        - r-base >=3.5.1,<3.5.2.0a0
        - r-bh
        - r-bit64
        - r-blob >=1.1.1
        - r-dbi >=1.0.0
        - r-hms
        - r-plogr >=0.2.0
        - r-rcpp >=0.11.4.2
        - r-withr
...
```
> 
> Is libpq also used during the compilation of r-rpostgres?
yes it is. During building the build requirements *and* host requirements are needed to build a conda package.
The above `meta.yaml` lists in its host requirements `libpq 10.5` explicitly.
```
requirements:
...
    host:
...
        - libpng 1.6.35 h84994c4_1002
        - libpq 10.5 h13b8bad_1000
        - libssh2 1.8.0 h1ad7b7a_1003
        - libstdcxx-ng 7.3.0 hdf63c60_0
...
```
hth

**Comment by jdblischak** [comment]
> The explicit pinning libpq of r-rpostgres is also given in the recipe/meta.yaml of the latest r-rpostgres package

OK. That makes sense.

> I think you have a local version of r-rpostgres which was compiled using libpq-11.4.

I don't have a local copy. I think the issue is the difference in build versions 1 and 1001. Build r351h29659fb_1001 properly pins libpq:

```
$ conda search r-rpostgres=1.1.1=r351h29659fb_1001 --info | grep libpq
  - libpq >=10.5,<11.0a0
```

But not build r351h9d2a408_1:

```
$ conda search r-rpostgres=1.1.1=r351h9d2a408_1 --info | grep libpq
  - libpq
```

And when I install r-rpostgres, the conda solver chooses r351h9d2a408_1:

```
conda create --yes -n test-rpostgres r-rpostgres
conda activate test-rpostgres
conda list libpq
# packages in environment at /home/jdb-work/miniconda3/envs/test-rpostgres:
#
# Name                    Version                   Build  Channel
libpq                     11.4                 hd9ab2ff_2    conda-forge
conda list r-rpostgres
# packages in environment at /home/jdb-work/miniconda3/envs/test-rpostgres:
#
# Name                    Version                   Build  Channel
r-rpostgres               1.1.1            r351h9d2a408_1    conda-forge
```

I'll merge this PR, but I do think it is strange that the conda solver is choosing the unpinned recipe.

Since you are knowledgeable about this recipe, could you please add yourself as a maintainer? You can add `[skip ci]` to the commit message to prevent the builds from restarting.

**Comment by jdblischak** [comment]
Hmmm...apparently `[skip ci]` doesn't work with Azure. It would have been nice if they'd used that convention as well.

@fhoehle Thanks for the PR!

**Pull request merged**
